baseURL = "https://caishuyue.com"
# title = "Hugo Themes"
author = "Shuyue Cai"
copyright = "Copyright © 2022"
paginate = 3
languageCode = "en"
DefaultContentLanguage = "en"
enableInlineShortcodes = true
# prevent build failures when using Hugo's Instagram shortcode due to deprecated Instagram API.
# See https://github.com/gohugoio/hugo/issues/7228#issuecomment-714490456
ignoreErrors = ["error-remote-getjson"]

# ------------------------------
theme = "paper"
title = "Shuyue's Blog"

[params]
cdnURL = "https://static.fifsky.com/shuyue"
color = 'linen'

#  twitter = 'nanxiaobei'
#  github = 'nanxiaobei'
#  instagram = 'nan.xiaobei'

avatar = 'https://static.fifsky.com/shuyue/images/avatar.png'
name = "Shuyue's Blog"
bio = 'Every day have progress, smiling face every day.'

# ------------------------------

# needed to  render raw HTML (e.g. <sub>, <sup>, <kbd>, <mark>)
[markup]
[markup.goldmark]
[markup.goldmark.renderer]
unsafe = true

[menu]

[[menu.main]]
identifier = "about"
name = "About"
url = "/about/"
weight = 10
[[menu.main]]
identifier = "contact"
name = "Contact"
url = "/contact/"
weight = 10

[taxonomies]
category = "categories"
tag = "tags"
series = "series"

[privacy]

[privacy.vimeo]
disabled = false
simple = true

[privacy.twitter]
disabled = false
enableDNT = true
simple = true

[privacy.instagram]
disabled = false
simple = true

[privacy.youtube]
disabled = false
privacyEnhanced = true

[services]

[services.instagram]
disableInlineCSS = true

[services.twitter]
disableInlineCSS = true
